### ISSUE TITLE
送出訂單後的錯誤

### ISSUE THREAD

**Issue by a461204a** [ALiangLiang/pchome-api#17]
沒動到api
只修改了config.json
成功加入購物車以後就跳出錯誤

C:\Users\MengYi\Desktop\test\pchome-api-master>node example.js
免運費
可貨到付款
TypeError: Cannot read property 'PK' of undefined
    at API.order (C:\Users\MengYi\Desktop\test\pchome-api-master\api\order.js:14:34)
    at async main (C:\Users\MengYi\Desktop\test\pchome-api-master\example.js:36:18)
TypeError: Cannot read property 'status' of undefined
    at main (C:\Users\MengYi\Desktop\test\pchome-api-master\example.js:47:14)

**Comment by ALiangLiang** [comment]
應該是修好了，Pchome的API有換過，測試過可以正確送出訂單。
